const SET_USERS = 'SET_USERS';
const SET_LOADING = 'SET_LOADING';
const DESTROY_USER = 'DESTROY_USER';
const TOGGLE_USER = 'TOGGLE_USER'

export {
  SET_USERS,
  SET_LOADING,
  DESTROY_USER,
  TOGGLE_USER
};
